config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :rooms do
    collection do
      get 'search'
    end
  end
  get 'users/:id/room' => 'users#room'
  get 'users/:id/reservation' => 'users#reservation'
  
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :room

    validates :user_id, presence: true, numericality: true
    validates :room_id, presence: true, numericality: true
    validates :number_of_people, numericality: true
    validates :start, presence: true
    validates :end, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user, optional: true
    has_many :reservations
    attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy
  attachment :profile_image

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def set_search
    @search = Room.ransack(params[:q])
    @search_rooms = @search.result.order(created_at: :desc).page(params[:page])
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :profile, :profile_image_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.all
    
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def show
    @reservation = Reservation.find(params[:id])
    @room = Room.find_by(params[:id])
    start_date = @reservation.start.strftime('%Y%m%d').to_i
    end_date = @reservation.end.strftime('%Y%m%d').to_i
    day = end_date - start_date
    @total = day * @reservation.number_of_people * @room.price
  end

  def new
    @reservation = Reservation.new(new_reservation_params)
    @room = Room.find(params[:id])
  end

  def create
    @reservation = Reservation.new(create_reservation_params)
    @room = Room.find(params[:reservation][:room_id])
    if @reservation.save
      redirect_to @reservation, notice: "新規予約をしました。"
    else
      render :new
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
    if @reservation.user != current_user
      redirect_to reservations_path(@reservation), alert: "不正なアクセスです。"
    end
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(create_reservation_params)
      redirect_to reservation_path(@reservation), notice: "予約内容を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy
    redirect_to "/users/#{@reservation.user.id}/reservation", notice: "予約を取り消しました。"
  end

  private
  def new_reservation_params
    params.permit(:user_id,:room_id, :start, :end, :number_of_people)
  end

  def create_reservation_params
    params.require(:reservation).permit(:user_id, :room_id, :start, :end, :number_of_people)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
before_action :authenticate_user!, except: [:index]
before_action :set_search

  def index
    @rooms = Room.all.order(id: "DESC")
    @q = Room.ransack(params[:q])
    @rooms = @q.result
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to room_path(@room), notice: "お部屋を投稿しました。"
    else
      render :new
    end
  end

  def edit
    @room = Room.find(params[:id])
    if @room.user != current_user
      redirect_to rooms_path, alert: "不正なアクセスです。"
    end
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to room_path(@room), notice: "お部屋を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to room_path(room), notice: "お部屋を削除しました。"
  end

  private

  def room_params
    params.require(:room).permit(:image, :address, :about, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def room
    @user = User.find(params[:id])
  end

  def reservation
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<main role="main">

<div id="carousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel" data-slide-to="0" class="active"></li>
    <li data-target="#carousel" data-slide-to="1" ></li>
    <li data-target="#carousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active" data-bs-interval="100">
      <%= image_tag 'hotel_room1.jpeg', class: "bd-placeholder-img bd-placeholder-img-lg d-block w-100", style: "max-height: 650px; object-fit:cover; object-position:50% 90%;" %>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <%= image_tag 'hotel_room2.jpeg', class: "bd-placeholder-img bd-placeholder-img-lg d-block w-100", style: "max-height: 650px; object-fit:cover; object-position:50% 10%" %>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <%= image_tag 'hotel_room3.jpeg', class: "bd-placeholder-img bd-placeholder-img-lg d-block w-100", style: "max-height: 650px; object-fit:cover;" %>
    </div>
  </div>
</div>

  <div class="container marketing my-5">
    <div class="row">
      <div class="col-lg-4">
        <%= image_tag 'kakuyasu.png', class:"bd-placeholder-img mb-3 shadow-md", style: "object-fit:cover;", width:"240", height:"180", role:"img" %>
        <h2>格安特集</h2>
        <p>旅行に行きたいけど今月はちょっと厳しいなあ...。 そんなあなたでも気軽に１万円以下で泊まれるリーズナブルなお部屋を集めました。</p>
        <p><%= link_to 'Check →', rooms_path(q: { price_lteq: '10000' }),class:"btn btn-secondary", role:"button" %></p>
      </div>
      <div class="col-lg-4">
        <%= image_tag 'hotel_room3.jpeg', class:"bd-placeholder-img mb-3 shadow-md", style: "object-fit:cover;", width:"240", height:"180", role:"img" %>
        <h2>ラグジュアリー特集</h2>
        <p>特別な日のためにちょっとした贅沢を。 日常では味わえないラグジュアリーな空間をお届けするお部屋を集めました。 記念日やお誕生日のご利用にオススメです。</p>
        <p><%= link_to 'Check →', rooms_path(q: { price_gteq: '10001' }),class:"btn btn-secondary", role:"button" %></p>
      </div>
      <div class="col-lg-4">
        <%= image_tag 'tokyo.png', class:"bd-placeholder-img mb-3 shadow-md", style: "object-fit:cover;", width:"240", height:"180", role:"img" %>
        <h2>東京特集</h2>
        <p>旅行をするならやっぱり都心が良い！ 都心にお住まいの方は勿論、地方からお越しの方でも楽しめる東京のホテルを集めました。</p>
        <p><%= link_to 'Check →', rooms_path(q: { address_cont: '東京' }),class:"btn btn-secondary", role:"button" %></p>
      </div>
    </div>

  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelMeetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script>
      $( document ).ready(function(){
      $('#mycarousel').carousel();
      });
    </script>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>
    
    <nav class="navbar navbar-expand-md navbar-dark bg-black">
      <%= link_to "HOTEL MEET",root_path, class: "navbar-brand display-block mx-2" %>
      <div class="collapse navbar-collapse justify-content-between mx-2">
        <ul class="nav navbar-nav mr-auto">
          <li class="nav-item active">
            <%= search_form_for @search do |f| %>
              <%= f.search_field :address_cont, url: rooms_path, type: "text", placeholder: "地域検索", class: "mt-1" %>
              <%= f.submit ("検索") , class: 'btn btn-light btn-sm mb-1'%>
            <% end %>
          </li>
          <%= link_to "お部屋一覧", rooms_path, class: 'btn btn-outline-light', style: "margin-left:10px;" %>
        </ul>
        <ul class="nav navbar-nav menu">
          <% if user_signed_in? %>
          <div class="dropdown show"  style="margin-right: 30px;">
            <a class="dropdown-toggle text-white text-decoration-none" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= attachment_image_tag current_user, :profile_image, fallback: "no-profile-image.png", class: "header_img", style: "max-height: 40px; max-width: 40px;" %> <%= current_user.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to "マイページ",user_path(current_user), class: "dropdown-item" %>
              <%= link_to "お部屋登録",new_room_path(current_user), class: "dropdown-item" %>
              <%= link_to "予約一覧","/users/#{current_user.id}/reservation", class: "dropdown-item" %>
              <%= link_to "登録一覧", "/users/#{current_user.id}/room", class: "dropdown-item" %>
              <%= link_to "ログアウト",destroy_user_session_path, method: :delete, class: 'dropdown-item border-top' %>
            </div>
          </div>
          </ul>
          <% else %>
            <li class="nav-item">
              <%= link_to "LOG IN",new_user_session_path, class: 'btn btn-secondary' %>
              <%= link_to "SIGN UP",new_user_registration_path, class: 'btn btn-secondary' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
  <%= yield %>
    <footer class="footer mt-auto py-2 bg-black">
      <div class="container">
        <span class="text-muted" style="color:white;">Hotel Meet.</span>
      </div>
    </footer>
  </body>
</html>

app/views/reservations/edit.html.erb
<div class="container-fluid py-5 h-100 bg-light">
  <%= form_with model: @reservation, local: true do |f| %>
    <h1 class="text-dark">Edit Reservation</h1>
      <hr>
    <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-3">
        <div class="text-center">
          <%= attachment_image_tag @reservation.room, :image,fallback: "no-image.png", class: "img-fluid img-thumbnail mt-4 mb-2", style: "width: 250px; z-index: 1" %>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="col">
            <h3>予約編集</h3>
            <div class="form-group">
                <%= f.label :start, "チェックイン", class: "col-lg-3 control-label" %>
                <div class="col-lg-12">
                <%= f.date_select :start, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label :end, "チェックアウト", class: "col-lg-3 control-label" %>
                <div class="col-lg-12">
                <%= f.date_select :end, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label :number_of_people, "宿泊者の人数", class: "col-lg-3 control-label" %>
                <div class="col-lg-6">
                <%= f.text_field :number_of_people, class: "form-control" %>
                </div>
            </div>
        </div>
      </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-lg-3 mt-4">
          <div class="d-flex justify-content-between">
              <div class="p-2 bd-highlight">
                  <%= link_to "戻る", reservation_path(@reservation), class:"btn btn-outline-dark btn-lg" %>
              </div>
              <div class="p-2 bd-highlight">
                <%= link_to "削除", reservation_path, method: :delete, class:"btn btn-secondary btn-lg" %>
              </div>
              <div class="p-2 bd-highlight">
                  <%= f.submit '更新', class: "btn btn-secondary btn-lg" %>
              </div>
          </div>
        </div>
      </div>
   </div>
   <% end %>
</div>

app/views/reservations/show.html.erb
<main role="main">
<div class="container-fluid py-4 h-100 bg-light">
  <h1 class="text-dark">Reservation About</h1>
  <hr>
<div class="row d-flex justify-content-center align-items-center h-100">
<div class="col col-lg-9 col-xl-5">
<div class="card shadow-sm">
  <%= attachment_image_tag @reservation.room, :image, fallback: "no-image.png", class: "card-img-top" %>
  <div class="card-body">
    <p class="card-title">チェックイン</p>
    <h4><%= @reservation.start %></h4>
    <p class="card-title">チェックアウト</p>
    <h4><%= @reservation.end %></h4>
    <p class="card-title">宿泊者人数</p>
    <h4><%= @reservation.number_of_people %> 名様</h4>
    <p class="card-title">合計</p>
    <h5><%= @total %>円</h5>
    <div class="d-grid gap-2 d-md-flex justify-content-between">
    <% if user_signed_in? %>
    <div class="mr-auto pt-2 bd-highlight">
    <h3>
    <%= link_to user_path(@room.user_id) do %>
      <%= attachment_image_tag @reservation.user, :profile_image, fallback: "no-profile-image.png", class: "profile_image", style: "max-height: 50px; max-width: 50px;" %>
    <% end %>
    <span class="pl-3"><%= @reservation.user.username %></span>
    </h3>
    </div>
    <div class="p-2 bd-highlight">
        <%= link_to "戻る", rooms_path,class:"btn btn-secondary btn-lg" %>
          <% if @reservation.user.id == current_user.id %>
            <%= link_to "編集", edit_reservation_path(@reservation),class:"btn btn-secondary btn-lg" %>
          <% end %>
        <% else %>
        <div class="mr-auto pt-2 bd-highlight">
        <%= link_to "戻る", user_rooms_path,class:"btn btn-secondary btn-lg" %>
        </div>
        <div class="p-2 bd-highlight">
          <%= link_to "ログイン",user_session_path,class:"btn btn-secondary btn-lg" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>
</main>

app/views/rooms/edit.html.erb
<div class="container-fluid pt-3 bg-light">
      <%= form_with model: @room do |f| %>
    <div class="col vh-100">
        <h1 class="text-dark">Edit Room</h1>
      <hr>
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-lg-3">
        <div class="text-center">
          <%= attachment_image_tag @room, :image, fallback: "no-image.png", class: "img-fluid img-thumbnail mt-4 mb-2", style: "width: 250px; z-index: 1" %>
          <h6>Upload a room photo...</h6>
          <%= f.attachment_field :image, class: "form-control" %>
        </div>
      </div>
      
      <div class="col-lg-5">
        <div class="col">
            <h3>お部屋編集</h3>
            <div class="form-group">
                <%= f.label :address, "住所", class: "col-lg-3 control-label" %>
                <div class="col-lg-12">
                <%= f.text_area :address, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label :about, "お部屋詳細", class: "col-lg-3 control-label" %>
                <div class="col-lg-12">
                <%= f.text_area :about, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label :price, "1泊あたりの料金", class: "col-lg-3 control-label" %>
                <div class="col-lg-6">
                <%= f.text_field :price, class: "form-control" %>
                </div>
            </div>
        </div>
      </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-lg-5 mt-4">
        <div class="d-flex justify-content-between">
            <div class="p-2 bd-highlight">
                <%= link_to "戻る", room_path(@room), class:"btn btn-outline-dark btn-lg" %>
            </div>
            <div class="p-2 bd-highlight">
              <%= link_to "削除",room_path(@room), method: :delete, class:"btn btn-secondary btn-lg" %>
            </div>
            <div class="p-2 bd-highlight">
              <%= f.submit '更新', class: "btn btn-secondary btn-lg" %>
            <% end %>
            </div>
        </div>
        </div>
   </div>
   </div>
</div>

app/views/rooms/show.html.erb
<main role="main">
<div class="container-fluid py-4 h-100 bg-light">
  <h1 class="text-dark">Rooms About</h1>
  <hr>
<div class="row d-flex justify-content-center align-items-center h-100">
  <div class="col col-lg-9 col-xl-5">
    <div class="card shadow-sm">
      <%= attachment_image_tag @room, :image, fallback: "no-image.png", class: "card-img-top" %>
      <div class="card-body">
        <p class="card-title">住所</p>
        <h4><%= @room.address %></h4>
        <p class="card-title">説明</p>
        <h5><%= @room.about %></h5>
        <p class="card-title">一泊あたり</p>
        <h5><%= @room.price %>円 /人</h5>
        <div class="d-grid gap-2 d-md-flex justify-content-between">
        <% if user_signed_in? %>
        <div class="mr-auto pt-2 bd-highlight">
          <h3>
          <%= link_to user_path(@room.user_id) do %>
            <%= attachment_image_tag @room.user, :profile_image, fallback: "no-profile-image.png", class: "profile_image", style: "max-height: 50px; max-width: 50px;" %>
          <% end %>
          <span class="pl-3"><%= @room.user.username %></span>
          </h3>
        </div>
        <div class="p-2 bd-highlight">
          <%= link_to "戻る", rooms_path,class:"btn btn-secondary btn-lg" %>
          <% if @room.user.id == current_user.id %>
            <%= link_to "編集", edit_room_path(@room),class:"btn btn-secondary btn-lg" %>
          <% end %>
        <% else %>
          <div class="mr-auto pt-2 bd-highlight">
          <%= link_to "戻る", rooms_path,class:"btn btn-secondary btn-lg" %>
          </div>
          <div class="p-2 bd-highlight">
            <%= link_to "ログイン",user_session_path,class:"btn btn-secondary btn-lg" %>
          </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% if user_signed_in? %>
  <div class="col col-lg-4">
    <div class="card shadow-sm">
      <div class="card-body">
        <%= form_with model: @reservation do |f| %>
        <h3>新規予約</h3>
        <hr>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :room_id, value: @room.id %>
          <div class="form-group">
              <%= f.label :start, "チェックイン", class: "col-lg-4 control-label" %>
              <div class="col-lg-12 py-2">
                <%= f.date_select :start, value: @reservation.start, class: "form-control" %>
              </div>
          </div>
          <div class="form-group">
              <%= f.label :end, "チェックアウト", class: "col-lg-4 control-label" %>
              <div class="col-lg-12 py-2">
                <%= f.date_select :end, value: @reservation.end, class: "form-control" %>
              </div>
          </div>
          <div class="form-group">
            <%= f.label :number_of_people, "宿泊者の人数", class: "col-lg-4 control-label" %>
              <div class="col-lg-7 py-2">
                <%= f.text_field :number_of_people, value: @reservation.number_of_people, class: "form-control" %>
              </div>
          </div>
          <div class="p-2" style="text-align: right;">
            <%= f.submit '確定', class: "btn btn-secondary btn-lg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>
</main>

app/views/shared/_error.html.erb
 <% if obj.errors.any? %>
   <% obj.errors.full_messages.each do |message| %>
     <ul>
       <li><%= message %></li>
     </ul>
   <% end %>
 <% end %>

app/views/users/reservation.html.erb
<main role="main bg-secondary">
  <div class="container-fluid h-100 bg-light">
    <div class="album py-5">
    <h1 class="text-dark">User reservations</h1>
      <hr>
        <div class="row mx-lg-n5 px-5">
            <% @user.reservations.each do |reserve| %>
                    <div class="col-md-3 ml-1">
                        <div class="card mb-5 shadow-sm">
                            <%= link_to reservation_path(reserve) do %>
                                <%= attachment_image_tag reserve.room, :image, fallback: "no-image.png", class: "bd-placeholder-img card-img-top", style: "width:100%; height:220px; object-fit:cover;" %>
                            <% end %>
                            <div class="card-body">
                                <h6 class="card-title">チェックイン</h6>
                                <h4><%= reserve.start %></h4>
                                <h6 class="card-text">チェックアウト</h6>
                                <h4><%= reserve.end %> 円</h4>
                                <h6 class="card-title">宿泊者数</h6>
                                <h4><%= reserve.number_of_people %>名</h4>
                                <div class="p-1" style="text-align: right;">
                                    <% if reserve.user.id == current_user.id %>
                                    <%= link_to "編集", edit_reservation_path(reserve),class:"btn btn-secondary btn-lg" %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
            <% end %>
        </div>
    </div>
  </div>
</main>

app/views/users/room.html.erb
<main role="main bg-secondary">
  <div class="container-fluid h-100 bg-light">
    <div class="album py-5">
    <h1 class="text-dark">User Rooms</h1>
      <hr>
        <div class="row mx-lg-n5 px-5">
            <% @user.rooms.each do |room| %>
                    <div class="col-md-3 ml-1">
                        <div class="card mb-5 shadow-sm">
                            <%= link_to room_path(room) do %>
                                <%= attachment_image_tag room, :image, fallback: "no-image.png", class: "bd-placeholder-img card-img-top", style: "width:100%; height:220px; object-fit:cover;" %>
                            <% end %>
                            <div class="card-body">
                                <h6 class="card-title">住所</h6>
                                <h4><%= room.address %></h4>
                                <h6 class="card-text">1泊あたり /人</h6>
                                <h4><%= room.price %> 円</h4>
                                <div class="d-grid gap-2 d-md-flex justify-content-between">
                                <h6 style="font-size: 12px; margin-top:15px;">※画像クリックで詳細へ</h6>
                                    <% if room.user.id == current_user.id %>
                                    <%= link_to "編集", edit_room_path(room),class:"btn btn-secondary btn-lg" %>
                                    <% elsif %>
                                    <%= link_to "予約",rooms_path,class:"btn btn-secondary btn-lg" %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
            <% end %>
        </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<section class="h-100">
  <div class="container-fluid py-5 h-100 bg-light">
  <h1 class="text-dark">User Profile</h1>
      <hr>
    <div class="row d-flex justify-content-center align-items-center h-100 pb-5">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-profile-image.png", class: "img-fluid img-thumbnail mt-4 mb-2", style: "width: 150px; z-index: 1" %>
              <% if @user.id == current_user.id %>
              <%= link_to "Edit profile",edit_user_path(@user), class:"btn btn-outline-dark",
                style:"z-index: 1;" %>
              <% end %>
            </div>
            <div class="ms-3" style="margin-top: 130px;">
              <h3><%= @user.username %></h3>
              <% if @user.id == current_user.id %>
              <p><%= @user.email %></p>
              <% end %>
            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa;">
            <div class="d-flex justify-content-end text-center py-1">
              <div class="px-3">
                <p class="mb-1 h5"><%= link_to @user.rooms.count, "/users/#{@user.id}/room", style: "text-decoration:none; color:#000;" %></p>
                <p class="small text-muted mb-0">Rooms</p>
              </div>
              <div>
                <p class="mb-1 h5"><%= link_to @user.reservations.count, "/users/#{@user.id}/reservation", style: "text-decoration:none; color:#000;" %></p>
                <p class="small text-muted mb-0">Reserving</p>
              </div>
            </div>
          </div>
          <div class="card-body p-4 text-black">
            <div class="mb-5">
              <p class="lead fw-normal mb-1">About</p>
              <div class="p-4" style="background-color: #f8f9fa;">
                <p class="font-italic mb-1"><%= @user.profile %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>